services:
  customer-service:
    build: ./sales-customer-service
    container_name: customer-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8001:8000"
    networks:
      - backend

  order-service:
    build: ./sales-order-service
    container_name: order-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CUSTOMER_SERVICE_URL=http://customer-service:8000
    depends_on:
      - customer-service
    ports:
      - "8002:8000"
    networks:
      - backend

  invoice-service:
    build: ./sales-invoice-service
    container_name: invoice-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ORDER_SERVICE_URL=http://order-service:8000
    depends_on:
      - order-service
    ports:
      - "8003:8000"
    networks:
      - backend

  payment-service:
    build: ./sales-payment-service
    container_name: payment-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - INVOICE_SERVICE_URL=http://invoice-service:8000
    depends_on:
      - invoice-service
    ports:
      - "8004:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge