events {}

http {

    upstream auth_service {
        server auth-service:8000;
    }

    upstream customer_service {
        server customer-service:8000;
    }

    upstream order_service {
        server order-service:8000;
    }

    upstream invoice_service {
        server invoice-service:8000;
    }

    upstream payment_service {
        server payment-service:8000;
    }

    upstream frontend_service {
        server frontend:3000;
    }

    server {
        listen 80;

        # headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;

        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;

        # ========================
        # AUTH SERVICE
        # ========================
        location /api/auth/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://auth_service;
        }

        # ========================
        # CUSTOMER SERVICE
        # ========================
        location /api/customers/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://customer_service;
        }

        # ========================
        # ORDER SERVICE
        # ========================
        location /api/orders/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://order_service;
        }

        # ========================
        # INVOICE SERVICE
        # ========================
        location /api/invoices/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://invoice_service;
        }

        # ========================
        # PAYMENT SERVICE
        # ========================
        location /api/payments/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://payment_service;
        }

        # ========================
        # FRONTEND
        # ========================
        location / {
            proxy_pass http://frontend_service;
        }

    }
}