events {}

http {
    server {
        listen 80;

        location /api/customers/ {
            proxy_pass http://customer-service:8000/customers/;
        }

        location /api/orders/ {
            proxy_pass http://order-service:8000/orders/;
        }

        location /api/invoices/ {
            proxy_pass http://invoice-service:8000/invoices/;
        }

        location /api/payments/ {
            proxy_pass http://payment-service:8000/payments/;
        }

        location / {
            proxy_pass http://frontend:3000;
        }
    }
}